# Generated by Django 3.0 on 2020-02-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
